GET http://localhost:3000/alice


###correct login
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "alice",
  "password": "nphan03"
}
###login wrong pass 
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "alice",
  "password": "npha"
}
###login with usernot found
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "skjkalsjdlfa",
  "password": "npha"
}
###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "username": "leila",
  "password": "leila123"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "username": "alice",
  "password": "nphan03"
}

###
POST http://localhost:3000/alice
Content-Type: application/json

{
  "date": "2022-06-23",
  "text": "listening to music"
}


###
DELETE http://localhost:3000/alice
Content-Type: application/json

{
  "id": "1"
}

###
PUT http://localhost:3000/alice
Content-Type: application/json

{
  "id": "2",
  "newText": "Updated diary"
}
