GET http://localhost:3000/alice


###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "alice",
  "password": "nphan03"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "ken",
  "password": "0987654321"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "username": "leila",
  "password": "leila123"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "username": "alice",
  "password": "nphan03"
}

###
POST http://localhost:3000/alice
Content-Type: application/json

{
  "diary": {
    "day": "27",
    "month": "June",
    "year": "2022",
    "text": "listening to music"
  }
}


###
DELETE http://localhost:3000/ken
Content-Type: application/json

{
  "id": "4652f0d2-f8c1-44c9-8427-c4b476dc8a60"
}

